### Get By Api Key
GET http://localhost:3000/tenants/api-key/019c272ca9857973ace855c977a62cd5?x-api-key=019c272ca9857973ace855c977a62cd5
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHhlOGJkMWVjY2FlZTA5MDEzOWQ3NjY2OTM3NzQ1ODFkYzE2NzRjYWFlYjE0N2JlZTY1ZGE1ZTA2NjBjMDVhMDlkIiwib3JnIjoiZGlkOmVudGl0eS1zdG9yYWdlOjB4ZGVmM2NiYjA5NTdmYjEzMWY5MzIzMzNkOTg4NjJiMzQ4NGQwYjIzZmJkODg5MDQ0MzhiZGZlMDM4NTdmZDU3OCIsInRpZCI6IjAxOWMyNzJjYTk4NTdiOWFhMTJjYmNjNjI0NTUxMDEzIiwiZXhwIjoxNzcwMTg3NjI1LCJzY29wZSI6InRlbmFudC1hZG1pbiJ9.YE-gWuqYBsOfuNXXtmDbrV5nQn-SI2S4YdfVWsm4CIK_VsTVu5X7bdu-9YaqzZcl9EWr3Y174OMrwx7kvQwcDQ
content-type: application/json
