### Health
GET http://localhost:3000/health
cookie: access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImF1dGgtc2lnbmluZyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHg3MDBjNDI5ZjlmZTM3NDViNTUyODQ5MGNhYTU1YjdmNDg3MTJmMzAxMDM5Mzk5NDkyMzY2ZTM1YTc1ZTJlZjgyIiwic3ViIjoiZGlkOmVudGl0eS1zdG9yYWdlOjB4NDE5OTkwZTEwODkzY2YwNzg3YWUzM2JhYmEyY2I2NTliZjNjYTM1ZjY0NjQwNzRkZDU4MTc5ZDc3NmM1ZDE2NCIsIm9yZyI6ImRpZDplbnRpdHktc3RvcmFnZToweDA4NmJmNDY5MDc0MWVlMmYzMjM0NWEyZWZmZjAwNjk2Njc5OTY5MWUwNWE2MTVkN2E0NTU2MjA4YjdhMzU5ZjMiLCJleHAiOjE3ODUzMDc3OTQsInNjb3BlIjoidXNlci1hZG1pbiIsInB2ZXIiOjB9.W-m51PkEdMSeNKmnlgO8SzjQEdfp119Qmf_0jqnrNn58AcBIgvWVewJ0aRJgnQyivsEbnMH3sziE_hW2cNy_Ag
content-type: application/json
