### Health
GET http://localhost:3000/health
cookie: access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImF1dGgtc2lnbmluZyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6aW90YTp0ZXN0bmV0OjB4MTQxYzc3ODMzNDUwYzY2ZmYwZjYyMjY3NmI3MGYyZWE3OWM1ODc3ZGYxNTgzY2IzNmMyNjU5MTMyZTI1ZWFlNiIsInN1YiI6ImRpZDppb3RhOnRlc3RuZXQ6MHhiYzg5ZmI0ZTc5ZjdjMWYyNmNhYjQ1Yzc0NmUyNzVmZmQ1NWM0NDMzZDQ0ZWM4YWUyZGI3OWE1N2I1ZmIwZWM4Iiwib3JnIjoiZGlkOmlvdGE6dGVzdG5ldDoweDllMjdlMWE1ZDdjNTBkNWVhNWIzZDU4YzE3MDZmNGU3MTY2OTg1MTkyY2VkM2EyMWFiNWM4MWMxODE3ODhiYjciLCJleHAiOjE3ODU3NDg2NjIsInNjb3BlIjoidXNlci1hZG1pbiIsInB2ZXIiOjB9.JqSEnD4bK2I8MoREuX2kQTXqolx0q7ZePbiVFRmh76seYtvkmQCeXAse8rPLh1fGUckVlhzzVAecYpZVZFm7Dg
content-type: application/json
