### Create negotiation
POST http://localhost:3000/rights-management/negotiations/offers
authorization: Bearer eyJraWQiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHhkODM0YTRlNjUxMjBlZTRmOTEwYWY3NjkxNzIzNzk0MDQwNDA5YThiMzI5OGEwMmE4YmFiZTZjMzk3Y2JjNmUwI2F0dGVzdGF0aW9uLWFzc2VydGlvbiIsInR5cCI6IkpXVCIsImFsZyI6IkVkRFNBIn0.eyJpc3MiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHhkODM0YTRlNjUxMjBlZTRmOTEwYWY3NjkxNzIzNzk0MDQwNDA5YThiMzI5OGEwMmE4YmFiZTZjMzk3Y2JjNmUwIiwibmJmIjoxNzcyMDkwMDU1LCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vc2NoZW1hLm9yZyJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiUGVyc29uIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7fX19.rZUAhWIrnF-UuXQiX6wbPScPJU23eC2ryJxTIxi_tL54GY5AEDFYGfRFURK6EOh5y1LVlbXzyqbnFGEpNWCsBw
content-type: application/json

{
	"@context": [
        "https://w3id.org/dspace/2025/1/context.jsonld"
    ],
    "@type": "ContractRequestMessage",
    "consumerPid": "urn:uuid:32541fe6-c580-409e-85a8-8a9a32fbe832",
	"providerPid": "urn:uuid:32541fe6-c580-409e-85a8-8a9a32fbe833",
    "offer": {
        "@type": "Offer",
        "@id": "urn:uuid:test-policy-offer-1"
    },
    "callbackAddress": "https://example.com/callback"
}
