### Get negotiation
GET http://localhost:3000/rights-management/policy/admin/urn:uuid:32541fe6-c580-409e-85a8-8a9a32fbe833
authorization: Bearer eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHhjOGM1YWMwODI2OTUxY2U1MTM2NzIyZTU3NjlkOTRlMTE4MzYyZDdlY2QzY2UxNzYxNTZjZGQwYWRiNDlkYTg0Iiwib3JnIjoiZGlkOmVudGl0eS1zdG9yYWdlOjB4ZThlYTg4ODRmZDgwODk3MzBkMWE3MzcxMWUwMWNiMzE0NTY2N2RjNDJjNTcwZGJhMWM5YjFkNWZlOTVkNTA1MCIsImV4cCI6MTc3MjA5Mzk0NCwic2NvcGUiOiJ0ZW5hbnQtYWRtaW4ifQ.3dsFBC1Hdjharv2158NVJmY7hNH97MNoT4UssKD83DymMjxdCkDOzqxPV_4b9Z5rhUvEP17zlJhSBDa8ylCRBw
content-type: application/json
