### Creates an auditable item graph vertex

POST http://localhost:3000/aig?x-api-key=019c272ca9857973ace855c977a62cd5
cookie: access_token=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHhlOGJkMWVjY2FlZTA5MDEzOWQ3NjY2OTM3NzQ1ODFkYzE2NzRjYWFlYjE0N2JlZTY1ZGE1ZTA2NjBjMDVhMDlkIiwib3JnIjoiZGlkOmVudGl0eS1zdG9yYWdlOjB4ZGVmM2NiYjA5NTdmYjEzMWY5MzIzMzNkOTg4NjJiMzQ4NGQwYjIzZmJkODg5MDQ0MzhiZGZlMDM4NTdmZDU3OCIsInRpZCI6IjAxOWMyNzJjYTk4NTdiOWFhMTJjYmNjNjI0NTUxMDEzIiwiZXhwIjoxNzcwMjgyMDI4LCJzY29wZSI6InRlbmFudC1hZG1pbiJ9.KdR7nFdWCaqylLkybCiVcl1H4xS7EwoBnifWvUkIjD0691yPz7qnxdrvOI3YMHZKtpHw44Bj2K1mZZsKMqm1Bw
content-type: application/json

{
}

