### Get an auditable item graph vertex verifying no signatures

GET http://localhost:3000/aig/aig:a6ca9eb0441727002f3ac20e467d95ec5ee1f86eaf2246f2ba5f6b8d3d1a91d6?includeChangesets=true
cookie: access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImF1dGgtc2lnbmluZyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHgyMWQ2Zjk5M2M3NDM4YWMwYWQ5NGY0NTllOWY4YjNiMzQwNGZmOWRlOGUzZGY4YjUyZDQ3YTNkNzNjMTRiOGM5Iiwic3ViIjoiZGlkOmVudGl0eS1zdG9yYWdlOjB4YjM2Zjg1MjkxNGJhOGFkYWVkNTIyM2Y1OWQyMjRkOGY5NGFiYWM2ZTQyOWMzMTdkYzVjYjdkNWVkMTQzZmE5MSIsIm9yZyI6ImRpZDplbnRpdHktc3RvcmFnZToweDJhYzdhYTI4ZmY0ZDUwMGRhNDIzNWNiZGU0ODFlOTIxZTAwMjExNGYwN2NiMTM5YTg2OGZiOTlmODYxOWU3YjkiLCJ0aWQiOiIwMWEwODRhZmVjYjY3YjA5YWJjY2NkNWZiMDNiN2IwMiIsImV4cCI6MTc4OTYyNzM1Miwic2NvcGUiOiJnbG9iYWwtYWRtaW4sdGVuYW50LWFkbWluLHVzZXItYWRtaW4iLCJwdmVyIjowfQ.vB51oDo0tcraHpTLMAzqqCPahJ7ZSUn9HUN_7cUOORx36OQffJRGRviubxF23DxrQsIUZP7BLFNGpmrwNBGsAQ


### Get an auditable item graph vertex verifying current signature

GET http://localhost:3000/aig/aig:a6ca9eb0441727002f3ac20e467d95ec5ee1f86eaf2246f2ba5f6b8d3d1a91d6?includeChangesets=true&verifySignatureDepth=current
cookie: access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImF1dGgtc2lnbmluZyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHgyMWQ2Zjk5M2M3NDM4YWMwYWQ5NGY0NTllOWY4YjNiMzQwNGZmOWRlOGUzZGY4YjUyZDQ3YTNkNzNjMTRiOGM5Iiwic3ViIjoiZGlkOmVudGl0eS1zdG9yYWdlOjB4YjM2Zjg1MjkxNGJhOGFkYWVkNTIyM2Y1OWQyMjRkOGY5NGFiYWM2ZTQyOWMzMTdkYzVjYjdkNWVkMTQzZmE5MSIsIm9yZyI6ImRpZDplbnRpdHktc3RvcmFnZToweDJhYzdhYTI4ZmY0ZDUwMGRhNDIzNWNiZGU0ODFlOTIxZTAwMjExNGYwN2NiMTM5YTg2OGZiOTlmODYxOWU3YjkiLCJ0aWQiOiIwMWEwODRhZmVjYjY3YjA5YWJjY2NkNWZiMDNiN2IwMiIsImV4cCI6MTc4OTYyNzM1Miwic2NvcGUiOiJnbG9iYWwtYWRtaW4sdGVuYW50LWFkbWluLHVzZXItYWRtaW4iLCJwdmVyIjowfQ.vB51oDo0tcraHpTLMAzqqCPahJ7ZSUn9HUN_7cUOORx36OQffJRGRviubxF23DxrQsIUZP7BLFNGpmrwNBGsAQ

### Get an auditable item graph vertex verifying all signatures

GET http://localhost:3000/aig/aig:a6ca9eb0441727002f3ac20e467d95ec5ee1f86eaf2246f2ba5f6b8d3d1a91d6?includeChangesets=true&verifySignatureDepth=all
cookie: access_token=eyJhbGciOiJFZERTQSIsImtpZCI6ImF1dGgtc2lnbmluZyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHgyMWQ2Zjk5M2M3NDM4YWMwYWQ5NGY0NTllOWY4YjNiMzQwNGZmOWRlOGUzZGY4YjUyZDQ3YTNkNzNjMTRiOGM5Iiwic3ViIjoiZGlkOmVudGl0eS1zdG9yYWdlOjB4YjM2Zjg1MjkxNGJhOGFkYWVkNTIyM2Y1OWQyMjRkOGY5NGFiYWM2ZTQyOWMzMTdkYzVjYjdkNWVkMTQzZmE5MSIsIm9yZyI6ImRpZDplbnRpdHktc3RvcmFnZToweDJhYzdhYTI4ZmY0ZDUwMGRhNDIzNWNiZGU0ODFlOTIxZTAwMjExNGYwN2NiMTM5YTg2OGZiOTlmODYxOWU3YjkiLCJ0aWQiOiIwMWEwODRhZmVjYjY3YjA5YWJjY2NkNWZiMDNiN2IwMiIsImV4cCI6MTc4OTYyNzM1Miwic2NvcGUiOiJnbG9iYWwtYWRtaW4sdGVuYW50LWFkbWluLHVzZXItYWRtaW4iLCJwdmVyIjowfQ.vB51oDo0tcraHpTLMAzqqCPahJ7ZSUn9HUN_7cUOORx36OQffJRGRviubxF23DxrQsIUZP7BLFNGpmrwNBGsAQ
