### Create negotiation
POST http://localhost:3000/rights-management/negotiations/request
authorization: Bearer eyJraWQiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHhjMWJjMjUxMDFjMjQ4YmM3Y2QyOGRhOWY4MjgzNGZkNzdhMzZiMmE3ZGIxYmY1MWNhYjJjM2ZmNjdhNmZhOTk4I2F0dGVzdGF0aW9uLWFzc2VydGlvbiIsInR5cCI6IkpXVCIsImFsZyI6IkVkRFNBIn0.eyJpc3MiOiJkaWQ6ZW50aXR5LXN0b3JhZ2U6MHhjMWJjMjUxMDFjMjQ4YmM3Y2QyOGRhOWY4MjgzNGZkNzdhMzZiMmE3ZGIxYmY1MWNhYjJjM2ZmNjdhNmZhOTk4IiwibmJmIjoxNzcyMTcwMzg3LCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vc2NoZW1hLm9yZyJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiUGVyc29uIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7fX19.xG_YMTCXRD3zgTNxZiWNZGd-s_BQueRd_Hf5OKYVAbmoI6whumo0jHPrswrFuFKcvtNAbSBgTV79D5EmQREcAQ
content-type: application/json

{
	"@context": [
        "https://w3id.org/dspace/2025/1/context.jsonld"
    ],
    "@type": "ContractRequestMessage",
    "consumerPid": "urn:uuid:32541fe6-c580-409e-85a8-8a9a32fbe833",
    "offer": {
        "@type": "Offer",
        "@id": "urn:uuid:test-policy-offer-1"
    },
    "callbackAddress": "https://example.com/callback"
}
