# Set the base image
FROM node:22

# Create the app directory
WORKDIR /app

# Copy the package.json
COPY package.json .

# Install dependencies including dev dependencies needed for merge-locales
RUN npm install --ignore-scripts

# Copy the rest of the files to the image
COPY . .

# Compile translation messages
RUN npm run merge-locales

# Remove dev dependencies to reduce image size
RUN npm prune --omit=dev

# Expose the port the app runs on
EXPOSE 3000

# Set the environment variables that will override the .env file in the package
ENV TWIN_NODE_HOST=0.0.0.0
ENV TWIN_NODE_PORT=3000
ENV TWIN_NODE_STORAGE_FILE_ROOT=/twin-node/data

# Start the server
CMD ["node", "src/index.mjs"]